### ISSUE TITLE
Error installing on Kubernetes

### ISSUE THREAD

**Issue by debjitk** [influxdata/helm-charts#105]
I am getting the following error

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Service.spec.ports[0].port): invalid type for io.k8s.api.core.v1.ServicePort.port: got "string", expected "integer"
```

**Comment by rawkode** [comment]
@debjitk which chart?

**Comment by debjitk** [comment]
influxdb

**Comment by rawkode** [comment]
The problem is your `bind_address` values. They should be integer port numbers. I believe these are poorly named variables, but I fear we're stuck with them for the time being.

Apologies for the confusion

**Comment by debjitk** [comment]
@rawkode Thanks. It solved the error.

**Comment by debjitk** [comment]
@rawkode I getting the following error on events log

`Readiness probe failed: Get http://172.x.x.x:8086/ping: dial tcp 172.x.x.x:8086: connect: connection refused`
