### ISSUE TITLE
The collectd service uses TCP when it should use UDP

### ISSUE THREAD

**Issue by stephenliang** [influxdata/helm-charts#107]
The [collectd service template](https://github.com/influxdata/helm-charts/blob/master/charts/influxdb/templates/service.yaml#L28) does not specify the UDP protocol and therefore launches as TCP. However, the [collectd service uses UDP](https://docs.influxdata.com/influxdb/v1.8/supported_protocols/collectd/) and not TCP. Manually editing the deployment to use UDP allowed traffic to flow in.

**Comment by russorat** [comment]
@s12chung thanks for opening! Would you be comfortable opening a PR for this?

**Comment by s12chung** [comment]
@russorat think you mean @stephenliang ?

**Comment by russorat** [comment]
🤦  yep! thanks

**Comment by aureq** [comment]
Hi @russorat 

I've created a a PR (#125) to address this issue as it's currently blocking my work. Could you please review my changes?
The changes are trivial.

Thanks
