### ISSUE TITLE
[influxdb] documentation issue

### ISSUE THREAD

**Issue by gboor** [influxdata/helm-charts#122]
Under the paragraph where it talks about starting with auth enabled, it states;

`In values.yaml, change .Values.config.http.auth_enabled to true.`

With the new chart, this should be auth-enabled instead of auth_enabled. auth_enabled will do nothing, as it's copied into the influxdb config 1 on 1.

**Comment by Deepika-23** [comment]
Hi, I submitted a PR for this issue. This is my first request, kindly let me know if any changes are required.
Thanks.

**Comment by rawkode** [comment]
#126
