### ISSUE TITLE
[influxdb-enterprise] config reference error

### ISSUE THREAD

**Issue by chobbs** [influxdata/helm-charts#127]
Misalignment of how the values are [expected to be defined](https://github.com/influxdata/helm-charts/blob/master/charts/influxdb-enterprise/values.yaml#L157-L158) and how they are [referenced](https://github.com/influxdata/helm-charts/blob/master/charts/influxdb-enterprise/templates/data-statefulset.yaml#L53-L55) (also for meta, expected config and referenced in chart). Changing the references to 
`.Values.[meta|data].https.secret.key` appears to have fix the issue.

**Comment by rawkode** [comment]
@chobbs do you want to submit a PR?

**Comment by chobbs** [comment]
PR submitted - https://github.com/influxdata/helm-charts/pull/135
