### ISSUE TITLE
[telegraf] Tolerations missing

### ISSUE THREAD

**Issue by bappr** [influxdata/helm-charts#142]
Hey guys,
tolerations is missing on the telegraf chart so we can't deploy telegraf on a taint node.
I can handle the PR if needed.
Thanks

**Comment by rawkode** [comment]
@bappr we'd welcome that change. Let me know if you need any help, or if you're short on time 😃

**Comment by bappr** [comment]
Cool https://github.com/influxdata/helm-charts/pull/143
Here u go

**Comment by timhallinflux** [comment]
closed via #143
