### ISSUE TITLE
Allow image SHA and TAG to be specified from values.yaml

### ISSUE THREAD

**Issue by Mierpo** [influxdata/helm-charts#147]
Users of (edit: https://github.com/influxdata/helm-charts/tree/master/charts/influxdb2) may want to use a specific tag and specific sha of the image, to ensure helm upgrade commands download the correct image and update to the correct image.

**Comment by rawkode** [comment]
@Mierpo which chart?

**Comment by Mierpo** [comment]
https://github.com/influxdata/helm-charts/tree/master/charts/influxdb2

**Comment by rawkode** [comment]
Hi @Mierpo 

I'll get this sorted

**Comment by lazyoldbear** [comment]
Overriding the tag would be a nice thing, indeed. I miss it dearly.

**Comment by timhallinflux** [comment]
closed via #294
