### ISSUE TITLE
Can't install Telegraf Operator in EKS (kubeVersion validation failed)

### ISSUE THREAD

**Issue by leoblanc** [influxdata/helm-charts#150]
Hi all, I'm trying to deploy the Telegraf Operator in EKS but I face this validation error:

```
$ helm upgrade --install telegraf-operator --namespace monitoring influxdata/telegraf-operator
Release "telegraf-operator" does not exist. Installing it now.
Error: chart requires kubeVersion: >= 1.13.0 which is incompatible with Kubernetes v1.17.6-eks-4e7f64
```

As you can see, I'm running EKS/Kubernetes 1.17.6 which is higher than 1.13.0. I understand that [this validation is set here](https://github.com/influxdata/helm-charts/blob/master/charts/telegraf-operator/Chart.yaml#L20). Maybe this is a kind of Helm bug (EKS is a non-standard Kubernetes system in several ways). But, just in case, do you know if there is a workaround for this? Is it possible to "relax" this validation without forking the Helm Chart?

Thank you very much in advance!

**Comment by russorat** [comment]
@leoblanc thanks! what happens when you change that kubeVersion in the code? does it work?

**Comment by leoblanc** [comment]
@russorat Hi Russ, I apologize for my late reply, I was on holidays. I have cloned the repo and did some testing. I found a [similar issue](https://github.com/apache/openwhisk-deploy-kube/issues/424) and I have created [this PR](https://github.com/influxdata/helm-charts/pull/154) that adds support for EKS. Please review, thanks

**Comment by leoblanc** [comment]
So, just to be clear, I have confirmed that the new kubeVersion correctly works now:
![install](https://user-images.githubusercontent.com/25181059/89810200-0f8d4700-db13-11ea-8b05-f79517d7b1fe.png)

**Comment by sumo-drosiek** [comment]
@russorat, @leoblanc Any update on that issue? When can we expect the review/merge of the PR?

**Comment by leoblanc** [comment]
@sumo-drosiek I have signed the CLA. I'm waiting for [some clarification regarding the version to bump](https://github.com/influxdata/helm-charts/pull/154#issuecomment-686440300)

**Comment by leoblanc** [comment]
Got it, it's the Chart version, I bumped the version with a new commit
