### ISSUE TITLE
Expose InfluxDB data service as k8s nodeport

### ISSUE THREAD

**Issue by VY81** [influxdata/helm-charts#151]
Hi,
InfluxDB data service in helm chart is currently exposed as ClusterIP.

https://github.com/influxdata/helm-charts/blob/master/charts/influxdb-enterprise/templates/data-service.yaml

Could you please provide ability to create a NodePort as well?

This will help us in reaching the service from other tenants

Thanks,
VY

**Comment by rawkode** [comment]
Hi @VY81,

Sure. We can make this configurable 👍
