### ISSUE TITLE
[influxdb-enterprise] Add context to run services under different userID 

### ISSUE THREAD

**Issue by chobbs** [influxdata/helm-charts#152]
Looking to add template values to support setting different securityContext 

see example here:
`
{{- $name := include "base.name" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  labels:
    {{ include "base.labels.mulesoft" . | indent 4 | trim }}
spec:
  serviceName: {{ $name }}
  podManagementPolicy: {{ required ".Values.deployment.replicas.podManagementPolicy is required" .Values.deployment.replicas.podManagementPolicy }}
  replicas: {{ required ".Values.deployment.replicas.replicaCount is required" .Values.deployment.replicas.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
      dias-prov-k8s-am-ingestor-comp/id: idValue
  template:
    metadata:
      name: {{ $name }}
      labels:
        {{ include "base.labels.mulesoft" . | indent 8 | trim }}
        dias-prov-k8s-am-ingestor-comp/id: idValue 
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        runAsUser: 2020
        runAsGroup: 2020
        fsGroup: 2020`

**Comment by rawkode** [comment]
@chobbs I can't reproduce this error. Can you get me the configuration that was used that caused the services not to run?

**Comment by rawkode** [comment]
Can't reproduce
