### ISSUE TITLE
[telegraf-ds] add support for affinity

### ISSUE THREAD

**Issue by sfitts** [influxdata/helm-charts#166]
We need to deploy the telegraf daemonset into cluster's that belong to our customers.  In those cases we want to limit its deployment to specific nodes.  Unfortunately, the chart does not currently support setting affinity for the daemonset.

**Comment by rawkode** [comment]
@sfitts we'd welcome a PR with nodeSelector, affinity, and tolerations 👍

If you don't have time, I'll start on this sometime next week

**Comment by sfitts** [comment]
Working on that now.  FWIW, tolerations appears to already be there.  Just need to test it on our cluster, then I'll put up a PR.
