### ISSUE TITLE
[influxdb 2.0] Duplicate annotation key in admin setup job

### ISSUE THREAD

**Issue by sudermanjr** [influxdata/helm-charts#175]
In the admin setup hook for the influxdb2 chart, there's an issue with the way the annotations are setup.

https://github.com/influxdata/helm-charts/blob/7335fea9f22e73befded0aa0cbfefff560673dd8/charts/influxdb2/templates/job-setup-admin.yaml#L9-L10

According to the docs this should be more like

```
"helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
```

https://helm.sh/docs/topics/charts_hooks/#hook-deletion-policies

**Comment by rawkode** [comment]
Good catch, @sudermanjr. If you would like to contribute, we'd accept a PR. If not, I'll pick this up.

**Comment by sudermanjr** [comment]
I can drop a PR in later today.
