### ISSUE TITLE
[influxdb] Recomendations for both TCP and UDP loadbalancer with Metallb

### ISSUE THREAD

**Issue by mikebell** [influxdata/helm-charts#176]
Hey folks,

I'm running Metallb on a baremetal k8s cluster and want to use both TCP and UDP with InfluxDB to allow Proxmox to send metrics. What's the best way of doing this? I know k8s loadbalancers don't allow both TCP and UDP connections on the same resource so I'm unsure how to configure the chart to achieve this.

**Comment by rawkode** [comment]
Hi @mikebell,

From the `metallb` docs:

> Kubernetes does not currently allow multiprotocol LoadBalancer services. This would normally make it impossible to run services like DNS, because they have to listen on both TCP and UDP. To work around this limitation of Kubernetes with MetalLB, create two services (one for TCP, one for UDP), both with the same pod selector. Then, give them the same sharing key and spec.loadBalancerIP to colocate the TCP and UDP serving ports on the same IP address.

> The second reason is much simpler: if you have more services than available IP addresses, and you can’t or don’t want to get more addresses, the only alternative is to colocate multiple services per IP address.

Does this help?

https://metallb.universe.tf/usage/

**Comment by mikebell** [comment]
Yeah it does, I guess this isn't possible with the current Helm chart?

**Comment by alespour** [comment]
Closed as stale. Please reopen if still needs to be addressed.
