### ISSUE TITLE
[telegraf-ds] empty kubernetes dashboard using influxdb2

### ISSUE THREAD

**Issue by mgcrea** [influxdata/helm-charts#186]
I've just deployed a working `influxdb2` + `telegraf-ds` to monitor a kubenetes cluster (single host).

Everything works fine except the `kubernetes` dashboard is empty, while both `system` and `docker` are fine (imported from template).

Telegraf does push some `kubernetes_xxx` metrics but it looks like there might be a mismatch.

What is the proper course of action to have a working kubernetes dashboard?

Thanks

**Comment by russorat** [comment]
@mgcrea which kubernetes dashboard are you referring to? Could you post a screenshot?

**Comment by mgcrea** [comment]
Hope it helps:

<img width="941" alt="Screenshot 2020-09-15 at 23 46 33" src="https://user-images.githubusercontent.com/108273/93268677-e0bb5e00-f7ad-11ea-809d-b28d1adc28a0.png">
<img width="1402" alt="Screenshot 2020-09-15 at 23 46 44" src="https://user-images.githubusercontent.com/108273/93268678-e153f480-f7ad-11ea-9966-867016da577a.png">

**Comment by exelban** [comment]
The same problem(

**Comment by nsteinmetz** [comment]
@exelban @mgcrea did you select the right bucket ?

Last time I used it (some months ago), it worked as expected ; I don't remember if I had to do some extra setup for this one or not.

**Comment by nsteinmetz** [comment]
Ok I see: this dashbord is to be used with the telegraf chart (not `telegraf-ds`chart) as it relies on the `kube_inventory` plugin

* telegraf-ds chart is for cluster/node monitoring -> use kubernetes input plugin
* telegraf chart is more for workload monitoring -> use kube_inventory plugin

**Comment by nsteinmetz** [comment]
Seems the kubernetes node metrics is not provided from the UI.

You can import both dashboard from here : https://github.com/influxdata/community-templates/tree/master/k8s

**Comment by exelban** [comment]
I have selected the right bucket. I also have installed `kube_inventory`. These 2 community template works, but some charts inside them have missing data.

I take one chart, `Resource Requests CPU`. It's filtered by `resource_requests_millicpu_units`. But not `kubernetes` and `kube_inventory` does not report this parameter.

**Comment by nsteinmetz** [comment]
For kubernetes plugin, seems I don't have it either - I noticed that depending on your provider, you may not have all metrics available (for ex ovh managed k8s service use cinder for volumes but metrics are not available yet)

You can also compare with prometheus to see if it's a telegraf issue (plugin can't fetch the data but it is available) or a cluster issue (data is not available whatever telegraf or prometheus)

**Comment by exelban** [comment]
As I remember `telegraf-ds` has enabled `kubernetes` by default.

I'm on GKE.

**Comment by nsteinmetz** [comment]
> As I remember `telegraf-ds` has enabled `kubernetes` by default.

Yes my point was more there are 2 plugins, 2 dashboards - each of them suit different needs and may be confused with each other at a first glance. That why I precised which plugin are used in which charts (and so the related dashboards)

**Comment by exelban** [comment]
It looks like I figured out what is my problem. I declare `kube_inventory` but in the wrong place. So it's not reporting the stats to the telegraf.

Maybe someone can help me with configuration. I have installed `telegraf` as a DaemonSet, and a single instance of `telegraf`. And I don't know where exactly I must enable this plugin. I suppose in DaemonSet (because it must collect the data from all nodes). But in [docs](https://github.com/influxdata/helm-charts/tree/master/charts/telegraf-ds) to the DaemonSet there is a info that I cannot declare the new inputs. I must create my own DaemonSet or I can enable in some way inputs in these charts?

**Comment by exelban** [comment]
Maybe it will help someone. As I understand you need to have installed `telegraf-ds` to collect data from all nodes. Additionally, you need to enable a `kube_inventory` input in a single instance of telegraf. Both telegraf instances must point to the same bucket. As the result, you will receive a bucket with stats from kubernetes input (which are enabled by default in `telegraf-ds`). And the additional stats from `kube_inventory`. Both of these inputs required to show all charts.

**Comment by rawkode** [comment]
Great summary, @exelban 

I'm going to close this, as I don't think anything is required.

If I'm mistaken, please let me know.
