### ISSUE TITLE
[telegraf-operator] No support for helm2 (but declared)

### ISSUE THREAD

**Issue by sumo-drosiek** [influxdata/helm-charts#187]
Telegraf-operator helm charts declares support for `Helm v2 or later`, but `apiVersion: v2` is supported only by helm3. Either `Readme.md` or `Chart.yaml` should be updated

rel:
 
* https://helm.sh/docs/topics/charts/#the-apiversion-field
* https://github.com/influxdata/helm-charts/tree/master/charts/telegraf-operator#prerequisites

**Comment by rawkode** [comment]
As Helm 2 is EOL in November, we're not going to support Helm 2 for any new charts; and will actively migrate existing charts to Helm 3
