### ISSUE TITLE
What is the difference between this and the bitnami influx chart?

### ISSUE THREAD

**Issue by caleb15** [influxdata/helm-charts#204]
see https://github.com/bitnami/charts/tree/master/bitnami/influxdb

**Comment by rawkode** [comment]
Those chart are provided by another organisation, InfluxData doesn't contribute nor support those charts.

**Comment by caleb15** [comment]
I'm aware that it is provided by another organization. I'm wondering which
one I should use. I'm leaning towards the bitnami one currently as it has a
large amount of documentation in the readme
