### ISSUE TITLE
add support for prometheus import

### ISSUE THREAD

**Issue by devopstales** [influxdata/helm-charts#205]
add support for prometheus import

**Comment by rawkode** [comment]
@devopstales To which chart? Can you be more specific, please. 

Thank you

**Comment by devopstales** [comment]
to the telegraf-ds

**Comment by rawkode** [comment]
@devopstales If you want to discuss this, I'm be happy to chat and work out the best way to help you. Sorry this has taken so long.

Ping me and reopen :)
