### ISSUE TITLE
Helm Chart(s) for Telegraf

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/helm-charts#21]
We should provide one or more helm charts for installing Telegraf in a Kubernetes cluster. We should support a Kubernetes monitoring template as well as an Istio monitoring template.

**Comment by gitirabassi** [comment]
fixed byt https://github.com/influxdata/helm-charts/pull/16

**Comment by gitirabassi** [comment]
Istio is out of scope for this chart

**Comment by rawkode** [comment]
@rickspencer3 There's now `telegraf` and `telegraf-ds` in the charts repository.

`telegraf-ds` is an opinionated DaemonSet installation that monitors the underlying hosts and runs the `kubernetes` plugin

`telegraf` is a flexible "spec yourself" deployment

Does this satisfy this issue?
