### ISSUE TITLE
[telegraf-ds] Opinionated chart at odds with InfluxData's own recommendations

### ISSUE THREAD

**Issue by philomory** [influxdata/helm-charts#221]
The README.md for the `telegraf-ds` chart says,

> You cannot customize Telegraf inputs for this chart being the goal is to provide an opinionated configuration for monitoring Kubernetes nodes and global Kubernetes monitoring.

But, the recommendations in InfluxData's own documentation for Telegraf's `kubernetes` input plugin states:

> Use metric filtering options to exclude unneeded measurements and tags.

... to avoid issues with series cardinality.

Unfortunately, it's difficult or impossible (depending on your filtering needs) to actually follow that advice while using this chart, because:

1. You can't use `fieldpass`, `fielddrop`, `tagpass` or `tagdrop` on outputs,
2. You can't drop metrics using a processor plugin (as far as I can tell, anyway), and
3. You can't customize the inputs supplied by the chart.

Is there any possibility of making the chart less strict with it's opinions about inputs?

**Comment by rawkode** [comment]
Hi,

Yes, we know there's some challenges here. Generating TOML from options in the values file has become a large burden for the maintainers of this chart. 

It is likely we'll provide an escape hatch to drop in your own config, at the expense of removing the default 

I'm also looking at providing hooks to inject Starlark as a processor for each plugin.

Which option would you be more likely to use?

**Comment by philomory** [comment]
@rawkode Insofar as I'd not previously heard of Starlark, I'd probably start off with raw TOML, though Starlark does sound promising.

It's unfortunate that Helm itself isn't more easily extensible - Hashicorp has a tool of their own which uses Go templates, and for which they provide a simple `toToml` template function that works just like the existing `toYaml` function, but unfortunately there's no way to incorporate extra template functions into a chart, or even a Helm plugin, it needs to be a patch to Helm's source code.

Actually, poking around it looks like Helm [has a `toToml` function of it's own](https://github.com/helm/helm/blob//pkg/engine/funcs.go); though this function is undocumented (mostly because Helm's template function documentation is terrible - `toYaml` isn't really documented either, just used in examples), and [possibly buggy](https://github.com/helm/helm/issues/6539). Has we tried using this function to generate Telegraf configs before and found it doesn't work, or has it just not been tried?

**Comment by rawkode** [comment]
@philomory Oh, interesting. That could be a good approach instead of the current conditional approach.

I'll test it with a few comments in the coming days. If you get the chance too also, feedback would be greatly appreciated.

**Comment by dlaidlaw** [comment]
It looks like Helm uses [this project](https://github.com/BurntSushi/toml) for generating TOML, which has some extra doc there. The helm source has
```golang
// toTOML takes an interface, marshals it to toml, and returns a string. It will
// always return a string, even on marshal error (empty string).
//
// This is designed to be called from a template.
func toTOML(v interface{}) string {
	b := bytes.NewBuffer(nil)
	e := toml.NewEncoder(b)
	err := e.Encode(v)
	if err != nil {
		return err.Error()
	}
	return b.String()
}
```

**Comment by philomory** [comment]
So, using `toToml` does seem to work extremely well, though you have to be careful how you format your YAML. I'll have a PR in a couple of days.

**Comment by philomory** [comment]
Urgh, unfortunately this isn't as great as I thought. Due to [an underlying bug in the YAML parser used by Helm](https://github.com/helm/helm/issues/8978), Helm will never return any integers from values files, only floats. Thus, `toToml` will render `metrics_batch_size: 1000` as `metrics_batch_size = 1000.0`.

**Comment by rawkode** [comment]
@philomory Should we keep this open? Is there anything still to action?

**Comment by philomory** [comment]
@rawkode Unfortunately I think not. It _should_ be fixable, but the constellation of bugs in other services and libraries (some of which the library authors have stated they have no intention of ever fixing) makes it extremely unlikely. I'll close it. The workaround from PR#239 will have to suffice.
