### ISSUE TITLE
[influxdb2] Allow custom config via INFLUXD_CONFIG_PATH

### ISSUE THREAD

**Issue by mproffitt** [influxdata/helm-charts#238]
According to the documentation at [https://docs.influxdata.com/influxdb/v2.0/reference/config-options/](https://docs.influxdata.com/influxdb/v2.0/reference/config-options/), influxd may optionally have configuration stored at `${INFLUXD_CONFIG_PATH}/config.*`

It would be beneficial to expose this to the statefulset as an additional, configurable environment variable, defaulting to `/root/influxdbv2`, therefore presenting users with the opportunity to configure how influxdb2 starts.

**Comment by timhallinflux** [comment]
closed via #294
