### ISSUE TITLE
[influxdb2] persistance subPath

### ISSUE THREAD

**Issue by benjick** [influxdata/helm-charts#242]
There's no option for a `subPath` under persistence which would be nice to have to be able to share mounts. I'm running my persistent volumes in AWS EFS and it would be nice to not have to create a whole new EFS share just for influxdb.

Here's how Grafana does it: https://github.com/grafana/helm-charts/blob/64a97049f641a29ac68c598641b3331416ba35a0/charts/grafana/templates/_pod.tpl#L38-L40

**Comment by alespour** [comment]
Closed via #356
