### ISSUE TITLE
[influxdb] read-buffer: 8388608 results in 8.388608e+06

### ISSUE THREAD

**Issue by MikeMichel** [influxdata/helm-charts#255]
Larger numbers like 8388608  are translated to 8.388608e+06 at least for a udp config which is handled in https://github.com/influxdata/helm-charts/blob/master/charts/influxdb/templates/configmap.yaml#L147

Maybe related to https://github.com/helm/helm/issues/1707

**Comment by rawkode** [comment]
I don't believe there's anything we can do about this. Closing for now. If I am incorrect, please reopen and tag me @MikeMichel
