### ISSUE TITLE
influxdb2 service type cannot be edited from Values.yaml

### ISSUE THREAD

**Issue by Mierpo** [influxdata/helm-charts#260]
**Problem file:**

https://github.com/influxdata/helm-charts/blob/master/charts/influxdb2/templates/service.yaml

**Problem description:**

Users cannot edit service type to "NodePort" for example, since service.yaml hardcodes it to "ClusterIP".

**Solution (must be fixed in this repository, no work-around exists for end-users)**

Add a new field to Values.yaml for service.type and use this value in service.yaml.

**Comment by rawkode** [comment]
This was resolved by 70eb87496ed236e0c6733518b74f0911a0b9e63d
