### ISSUE TITLE
Defining custom output.health is broken

### ISSUE THREAD

**Issue by dbk-rabel** [influxdata/helm-charts#261]
Hi.

We have a custom output.health defined in our values.yaml. It seems that this is broken by

https://github.com/influxdata/helm-charts/commit/b447ad0591fc7b8535a4439fdbbf533dffee4d8c#diff-
4af3496e791b170874582850a89679e568911aad454f006ed81ba3f08d62f7fb

As is reflected by another Commit regarding the predefined output.health:

https://github.com/influxdata/helm-charts/commit/18e6b8cb505c610a04e0de39e0ba8868517296ad#diff-a4e7c60866d11aca1edb18738b28e31cdd06a327975ef57c76a6fc6001f2d4c1

So I think the first commit is not quite correct. It would be nice to have this fixed, but I don't know too much about toml and Telegraf configuration. So if you could help, that would be great.

Also ideas for a workaround would be appreciated.

Yours
  David

**Comment by dbk-rabel** [comment]
Sorry, my PR seems to have a problem. Not sure if I will find the time to correct that. :(

**Comment by rawkode** [comment]
Not your fault. I'm fixing 👍🏻
