### ISSUE TITLE
Volume definition doesn't work in chronograf

### ISSUE THREAD

**Issue by sburton-sumo** [influxdata/helm-charts#263]
I put out a [PR](https://github.com/influxdata/helm-charts/pull/259) to fix this issue but it hasn't gotten any attention so I'm filing a bug report as well.

The volume definition in the Chronograf chart has a typo (`.values` instead of `.Values`).  Consequently enabling a volume attachment causes a helm rendering error.  For more details, see the PR https://github.com/influxdata/helm-charts/pull/259

**Comment by rawkode** [comment]
Apologies, my notifications on GH can get a little crazy and I miss stuff. Please feel free to tag me on PRs if you don’t get a response

**Comment by alespour** [comment]
Already closed via #259
