### ISSUE TITLE
[influxdb2] -r flag missing in official chart v >1.0.13

### ISSUE THREAD

**Issue by ondrej-ivanko** [influxdata/helm-charts#268]
Hi guys @rawkode @timhallinflux ,

I just noticed when i tried to use the -r flag that I proposed here: [commit](https://github.com/influxdata/helm-charts/commit/53f68e0b4f82aba85f1a80b331f540fcc7ba0934#diff-753c52c39f605363111b5f3d76e066a4dd4742609afc628e991a7de82182d37c) using latest chart v 1.0.15, that it's not part of the jobs_setup_admin.yaml. Is this change possibly not yet propagated to latest chart in influxdata repo, yet?

I'm using helm pull infludata/influxdb2 --untar and than checking content of values.yaml and & templates/jobs_setup_admin.yaml

Thank you for the answer.

**Comment by rawkode** [comment]
Sometimes the release process fails. I've triggered a rebuild #269

**Comment by rawkode** [comment]
@ondrej-ivanko Is this fixed?

**Comment by ondrej-ivanko** [comment]
Hi @rawkode it's ok now. since chart version 1.0.16. Thanks.
