### ISSUE TITLE
telegraf-ds: apparmor denies ptrace operation

### ISSUE THREAD

**Issue by paulchoi** [influxdata/helm-charts#284]
We need a better solution for Telegraf-ds running on Kubernetes nodes with apparmor. Apparmor is denying `ptrace` operations.
Seeing these messages on Kubernetes nodes.

```
Mar 09 18:40:20 app006 kernel: audit: type=1400 audit(1615315220.260:470805): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=1905963 comm="telegraf" requested_mask="read" denied_mask="read" peer="unconfined"
```

For now, I've added `container.apparmor.security.beta.kubernetes.io/telegraf-ds: unconfined` to `spec.template.metadata.annotations` for the Daemonset.

**Comment by alespour** [comment]
Profile management is beyond the helm charts scope I guess, but if the chart would support annotations, then apparmor profile could be referenced (or disabled at all as shown above) would be acceptable solution?

**Comment by alespour** [comment]
Apparmor profile management is beyond the helm charts scope, but the chart with pod annotations support would allow to specify profile reference.
