### ISSUE TITLE
telegraf-ds: "could not initialize input inputs.chrony"

### ISSUE THREAD

**Issue by holmesb** [influxdata/helm-charts#287]
Hi,

When I add the chrony input:
```
override_config:
  toml: |+
    ...
    [[inputs.chrony]]
```

My telegraf pods fail to start:
`2021-03-17T18:10:39Z E! [telegraf] Error running agent: could not initialize input inputs.chrony: chronyc not found: verify that chrony is installed and that chronyc is in your PATH`

chronyc is installed and it's in the PATH on the Kubernetes node (in /usr/bin/chronyc).  If I remove this input, the pod starts fine.  I even tried editing the DS, and adding: ``spec.template.spec.containers[0].securityContext.privileged = true``.  Same error.

Anyone got this chart working with the chrony input?  Node is Ubuntu, k8s is 1.19.7.

Many thanks

**Comment by nsteinmetz** [comment]
but it's not in the container - so normal beahviour I would say.

**Comment by alespour** [comment]
As @nsteinmetz writes, `chronyc` is not in the container.

What I got working is mounting **statically** linked `chronyc` binary into container (using manually edited DS, but there's pending PR #446 to allow that via values) together with using `hostNetwork` policy (unfortunately `inputs.chrony` has no option to specify server so it connects to localhost:323).

```yaml
  ...
      volumeMounts:
      - mountPath: /usr/local/bin/chronyc
        name: chronyc
        readOnly: true
...
    volumes:
    - hostPath:
        path: /usr/local/bin/chronyc
        type: File
      name: chronyc
...
```

`helm install --set hostNetwork=true telegraf-ds charts/telegraf-ds`


```bash
/ # telegraf --test --input-filter chrony
2022-03-22T12:21:02Z I! Starting Telegraf 1.21.4
2022-03-22T12:21:02Z I! Using config file: /etc/telegraf/telegraf.conf
2022-03-22T12:21:02Z I! Loaded inputs: chrony
2022-03-22T12:21:02Z I! Loaded aggregators: 
2022-03-22T12:21:02Z I! Loaded processors: 
2022-03-22T12:21:02Z W! Outputs are not used in testing mode!
2022-03-22T12:21:02Z I! Tags enabled: host=master-node
> chrony,host=master-node,leap_status=normal,reference_id=C19E160D,stratum=2 frequency=-498.541,last_offset=0.000250461,residual_freq=0.025,rms_offset=0.001701067,root_delay=0.050479379,root_dispersion=0.004782866,skew=0.852,system_time=0.000295491,update_interval=1036.1 1647951662000000000
```
