### ISSUE TITLE
influxdb2 helm chart need update to dockerhub version of influxdb2

### ISSUE THREAD

**Issue by kOstovic** [influxdata/helm-charts#288]
Current Helm chart reference quay.io version of influxdb2 docker. Helm need's to be updated to official release from dockerhub. Moreover this isn't just update image and chart names in templates, but also update of job section and liveness/readiness probe because it fails on them too. Also there is no way to use env variables which means some things like upgrade is not supported. 

Therefor there is need to refactor job section and add env section in deployment of stateful set

**Comment by timhallinflux** [comment]
closed via #294
