### ISSUE TITLE
influxdb setDefaultUser not working on arm platform

### ISSUE THREAD

**Issue by eoprede** [influxdata/helm-charts#305]
I ran into this issue when trying to deploy influxdb on arm64 platform. While influxdb image works just fine, the appropriate/curl image it references to set user with password does not have an arm64 version and fails. Changing image to curlimages/curl:latest seems to fix the issue.

**Comment by mylesagray** [comment]
+1, also changed the image to `curlimages/curl:latest` to fix the issue:

https://github.com/mylesagray/home-cluster-gitops/blob/master/manifests/influxdb/values.yaml#L4-L6
