### ISSUE TITLE
[telegraf-ds] ServiceAccount bearer token points at wrong location

### ISSUE THREAD

**Issue by vzabawski** [influxdata/helm-charts#310]
According to [documentation](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/), service account token should be pointing at `/var/run/secrets/kubernetes.io/serviceaccount` instead of `/run/secrets/kubernetes.io/serviceaccount/token`. Current config produces the following error:
```2021-04-30T15:01:49Z E! [telegraf] Error running agent: could not initialize input inputs.kubernetes: open /run/secrets/kubernetes.io/serviceaccount/token: no such file or directory```

Replacing the value at configmap fixes pods.

**Comment by alespour** [comment]
Solved by #361
