### ISSUE TITLE
[influxdb2] helm chart creates a new admin-password/token even if bolt file is present

### ISSUE THREAD

**Issue by psauvage0** [influxdata/helm-charts#322]
When a bolt file is present (eg. persistence is used), the initialisation is skipped in the docker entrypoint. However the helm chart will generate a new token and password even in that case. This is confusing considering that the chart will tell you at the end of the deploy a new (useless) password even though you still need to use the old one.

**Comment by alespour** [comment]
Unfortunately helm chart has no way to find out if the instance has already been set up.
