### ISSUE TITLE
S3 optional endpoint-url is not optional

### ISSUE THREAD

**Issue by kadern0** [influxdata/helm-charts#328]
In Values.yaml
```
## Optional. Specify if you're using an alternate S3 endpoint.
```

But if you don't specify an `endpoint-url` this is what you get:
```
aws: error: argument --endpoint-url: expected one argument
```

If optional, [this line](https://github.com/influxdata/helm-charts/blob/0b7a0a1c8d590f7a27f88b855464945b8e40bb01/charts/influxdb/files/backup-retention-script.sh#L59) should be modified to prevent this error. Happy to submit a PR if you agree with that.

**Comment by alespour** [comment]
Apologies for the delayed response. PR is always appreciated :)
