### ISSUE TITLE
function "lookup" not defined

### ISSUE THREAD

**Issue by wansuyoo** [influxdata/helm-charts#338]
* Version
https://github.com/influxdata/helm-charts/releases/tag/influxdb2-2.0.1

* To reproduce
```
$ wget https://github.com/influxdata/helm-charts/releases/download/influxdb2-2.0.1/influxdb2-2.0.1.tgz
$ tar zxvf influxdb2-2.0.1.tgz
$ helm install influxdb2
$ Error: parse error in "influxdb2/templates/secret.yaml": template: influxdb2/templates/secret.yaml:10: function "lookup" not defined
```

* Addition
helm version v2.14.3

**Comment by gs11** [comment]
Please see https://github.com/influxdata/helm-charts/tree/master/charts/influxdb2#prerequisites
> **Prerequisites**
> * Helm v3 or later

**Comment by reydelleon** [comment]
I'm seeing the exact same error and I got Helm > v3.
`version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`

**Comment by reydelleon** [comment]
A Helm version of 3.2 or newer is necessary to install the chart. There was a bug in Helm causing this.

**Comment by alespour** [comment]
Closing as prerequisite issue.
