### ISSUE TITLE
Update Chronograf Helm chart to support connecting to etcd backend

### ISSUE THREAD

**Issue by russorat** [influxdata/helm-charts#37]
Chronograf 1.8 adds the ability to use etcd as the backing store with the following config options:
https://docs.influxdata.com/chronograf/v1.8/administration/config-options/#etcd-options

We should add those to the helm chart

**Comment by naseemkullah** [comment]
Hi @russorat, I believe any config options can be passed along env var format: https://github.com/influxdata/helm-charts/blob/0de8813b40918aaebc1fe2a3bb1a7ebcaa8711b4/charts/chronograf/values.yaml#L99-L105
