### ISSUE TITLE
Backup failing after upgrade to influxdb 2.0.9

### ISSUE THREAD

**Issue by isatfg** [influxdata/helm-charts#376]
Hi

The influxdb backup cron was working fine on image tag 1.8.6-alpine, however when I upgrade influxdb to 2.0.9-alpine the cronjob pod goes into a Init:CrashLoopBackOff. I belive it's due to the 1.8.6 backup command differs from the 2.0.9. Is there a fix for this?

**Comment by alespour** [comment]
Please see [2.x backup command](https://docs.influxdata.com/influxdb/v2.1/reference/cli/influx/backup/) docs.

**Comment by isatfg** [comment]
Thank you @alespour , I have realised the backup command is  not the same also that there is a helm chart for influxdb2 which I am now using. FYI the influxdb2 helm chart does not have a backup option however I have managed to get it working using this backup with the influxdb2 commands
