### ISSUE TITLE
Will there be major changes in helm chart for deploying Influx 2?

### ISSUE THREAD

**Issue by RohitR1** [influxdata/helm-charts#4]
When will charts be upgraded to influx 2? 

Does [image upgrade](https://github.com/influxdata/helm-charts/blob/master/charts/influxdb/values.yaml#L5) to 2 work or will new chart be created?

**Comment by rawkode** [comment]
I've been using the chart below with success, and we'll officially support InfluxDB 2 in this repo as we approach GA

https://github.com/rawkode/influxdb-examples/tree/master/influxdbv2-helm-chart

**Comment by rawkode** [comment]
The InfluxDB 2 chart is now available
