### ISSUE TITLE
Readiness/Liveness probes not configurable properly

### ISSUE THREAD

**Issue by RalfWenzel** [influxdata/helm-charts#406]
When using the metrics configuration like below, i would expect that a liveness/readyness probe is configured. But this is not the case.

Example values.yaml:

```
metrics:
  health:
    enabled: true
    threshold: "5000.0"
```

This setup creates an ``outputs.health`` configuration and enables the required port in the service object.

But the readiness/liveness probes are only created when there is an ``outputs.health`` plugin configured in the config section. 

The relevant part from deployment.yaml is below

```
{{- range $objectKey, $objectValue := .Values.config.outputs }}
        {{- range $key, $value := . -}}
        {{- $tp := typeOf $value -}}
        {{- if eq $key "health" }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ trimPrefix "http://:" $value.service_address | int64 }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ trimPrefix "http://:" $value.service_address | int64 }}
        {{- end }}
        {{- end }}
        {{- end }}
```

Whilst it is possible to configure such an output anoter service address (not port 8888) must be used which renders the outputs.health created in the metrics section useless.

Did i get somwthing wrong?

**Comment by alespour** [comment]
I agree, probes should be enabled when either `metrics.health` is enabled or `output.health` is configured.
