### ISSUE TITLE
[influxdb2] Set automountServiceAccountToken

### ISSUE THREAD

**Issue by StefanAbl** [influxdata/helm-charts#428]
I ran kubeaudit against my k3s cluster in which I deployed the influxdb2 chart. It reports the following:
```
-- [error] AutomountServiceAccountTokenTrueAndDefaultSA
   Message: Default service account with token mounted. automountServiceAccountToken should be set to 'false' on either the ServiceAccount or on the PodSpec or a non-default service account should be used.
```
However I cannot find an option to specify this in the values.yaml file of the chart. I also believe automountServiceAccountToken should be set to false by default in the chart.

Thanks for your time and help.

helm list output:
```
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                  	APP VERSION
influxdb2	default  	6       	2022-03-03 21:15:04.043523702 +0000 UTC	deployed	influxdb2-2.0.9        	2.1.1
```

**Comment by alespour** [comment]
Other charts use non-default service account by default, this chart is missing it.
