### ISSUE TITLE
Duplicate roleRef in Kapacitor's rolebinding.yaml

### ISSUE THREAD

**Issue by mwmahlberg** [influxdata/helm-charts#431]
https://github.com/influxdata/helm-charts/blob/135747bb3e9adf8dad735e19081e2a7aefcee2d4/charts/kapacitor/templates/rolebinding.yaml#L16-L27

This serves no purpose and causes problems with linters and any other tool that does plausibility checks, such as kustomize.

**Comment by alespour** [comment]
Closed via #432
