### ISSUE TITLE
Make ingress path configurable

### ISSUE THREAD

**Issue by jehie** [influxdata/helm-charts#45]
Hi,

Would it be possible to make the influxdb chart Ingress path configurable from the values file? At the moment the value is hard coded into "/". 

I have some use cases to change the path and also it does not work well with aws-alb-ingress-controller, which then creates an Application Load Balancer, that only forwards request from '/', so calling /query does not work.

`
{{- end }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "influxdb.fullname" . }}
          servicePort: 8086
{{- end -}}
`

**Comment by russorat** [comment]
@jehie thanks! would this be something you'd be willing to help contribute?

**Comment by jehie** [comment]
Sure - I will sort the CLA and try to get this done this week :)

**Comment by jgeth** [comment]
Would appreciate this for Chronograf chart as well. `/` is treated differently by different Ingress controllers. See related: https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/
