### ISSUE TITLE
Pod not starting on influxdb2 fresh install

### ISSUE THREAD

**Issue by catalinmer** [influxdata/helm-charts#471]
Hi,
I tried to install the influxdb2 chart but the pod from the statefulset doesn't start, looks like some init container might be needed. The log of the pod is:
```Command "print-config" is deprecated, use the influx-cli command server-config to display the configuration values from the running server
Command "print-config" is deprecated, use the influx-cli command server-config to display the configuration values from the running server
Command "print-config" is deprecated, use the influx-cli command server-config to display the configuration values from the running server
chmod: /etc/influxdb2: Operation not permitted
chown: /var/lib/influxdb2: Operation not permitted
chown: /var/lib/influxdb2/lost+found: Operation not permitted
```
Am I missing something? any quick fix?
Thank you

**Comment by catalinmer** [comment]
persistence:
    enabled: true

**Comment by alespour** [comment]
So the default, right. And the persistence volume config? The `Operation not permitted` error has something to do with the volume I'd guess.

**Comment by catalinmer** [comment]
it is with default settings. the PVC is fine, created and attached to the pod. But the pod is unable to ....manage the files by the look of it. just running `helm install influx influxdata/influxdb2` with default options

**Comment by alespour** [comment]
I mean PV itself.

**Comment by catalinmer** [comment]
Looks like it needs a security context in order to have the mounted volume with the correct permissions. Adding:
```
securityContext:
    runAsUser: 1000
    runAsGroup: 1000
```
to values.yaml solves the problem.
