### ISSUE TITLE
initScripts: dont work

### ISSUE THREAD

**Issue by robbyq92** [influxdata/helm-charts#481]
Hi

i have the last chart (install today 14/06/2022) to influxdb with this version:

image:
  repository: influxdb
  tag: 2.2.0-alpine
  pullPolicy: IfNotPresent

i have this config in helm values for configurations:

`
initScripts:

  enabled: true

  scripts:

    init.sh: |+
      #!/bin/bash; sleep 10;
      set -e; sleep 10;
      influx bucket create \
        --name nano_better \
        --description nano_better \
        --token ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN} \
        --org ${DOCKER_INFLUXDB_INIT_ORG}
    init_oracle.sh: |+
      #!/bin/bash; sleep 10;
      set -e; sleep 10;influx bucket create --name nano_better  --description nano_better  --token ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}  --org ${DOCKER_INFLUXDB_INIT_ORG}
    init_unix.sh: |+
      #!/bin/bash; sleep 10;influx bucket create --name nano_better  --description nano_better  --token TOKEN   --org nano_better 
    init_core.sh: |+
      #!/bin/bash; sleep 10;influx bucket create --name nano_better  --description nano_better  --token TOKEN   --org nano_better 
    init_wintel.sh: |+
      #!/bin/bash; sleep 10;influx bucket create --name nano_better  --description nano_better --token TOKEN  --org nano_better ; influx bucket create --name nano_better  --description nano_better  --token nano_better   --org nano_better 
`

i try with sleep, without sleep, and nothing, in pod create in this directory /docker-entrypoint-initdb.d all init_xxx.sh but dont work i dont see my bucket.

**Comment by alespour** [comment]
This works for me. Make sure interpreter line is just `#!/bin/bash` and nothing else.

```yaml
    init.sh: |+
      #!/bin/bash
      set -e
      influx bucket create \
        --name nano_better \
        --description nano_better \
        --token ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN} \
        --org ${DOCKER_INFLUXDB_INIT_ORG}
```

Pod log:
```
2022-06-15T08:52:44.	info	Executing user-provided scripts	{"system": "docker", "script_dir": "/docker-entrypoint-initdb.d"}
/docker-entrypoint-initdb.d/init.sh:
ID			Name		Retention	Shard group duration	Organization ID		Schema Type
0ed70b438c62cd70	nano_better	infinite	168h0m0s		55e321d8083e4745	implicit
```

Buckets:
```
bash-5.1# influx bucket list
ID			Name		Retention	Shard group duration	Organization ID		Schema Type
286f34827746c4cb	_monitoring	168h0m0s	24h0m0s			55e321d8083e4745	implicit
9e6103bf533d8ac2	_tasks		72h0m0s		24h0m0s			55e321d8083e4745	implicit
40005d268f7b827e	default		infinite	168h0m0s		55e321d8083e4745	implicit
0ed70b438c62cd70	nano_better	infinite	168h0m0s		55e321d8083e4745	implicit

```

**Comment by yanehi** [comment]
Unfortunately, I have the same problem in a Kubernetes environment. The script is in the pod under docker-entrypoint-initdb.d but is not executed. However, when I log in to the pod and run the script manually, it works. There are no errors in the logs.

```
initScripts:
  enabled: true
  scripts:
    init.sh: |+
      #!/bin/bash
      set -e
      influx -username 'admin' \
        --password "${INFLUXDB_ADMIN_PASSWORD}" \
        --database 'db' \
        --execute "create user "${INFLUXDB_CUSTOMUSER_NAME}" with password '${INFLUXDB_CUSTOMUSER_PASSWORD}'"
```
