### ISSUE TITLE
telegraf optional secret(s)

### ISSUE THREAD

**Issue by cskinfill** [influxdata/helm-charts#53]
Add an option for a secret (or more) to be loaded by the telegraf deployment.

**Comment by russorat** [comment]
@cskinfill thanks! is this something you would be willing to help with?

**Comment by rawkode** [comment]
@cskinfill Which chart are you asking for this to be added?

**Comment by rawkode** [comment]
Hey @cskinfill, we're happy to add this functionality; but we need some more details.

Please reopen if you come back to this.
