### ISSUE TITLE
Chart repository empty

### ISSUE THREAD

**Issue by nicolas-geniteau** [influxdata/helm-charts#58]
Hello,

All charts from github pages repository have been removed:
https://github.com/influxdata/helm-charts/commit/eeb10e44f24b025d3ac5f35d63a5c926f7e06ab2

I didn't look how `helm/chart-releaser-action` works but It can be related to the github pages down:
https://www.githubstatus.com/

Thanks !

**Comment by lelithium** [comment]
Just run into this as well. In the meantime @nicolas-geniteau , you can get the pre-packaged charts from the Releases

**Comment by rawkode** [comment]
GitHub pages is down at there moment and that's not much we can do.

hopefully it'll be back up soon

**Comment by lelithium** [comment]
@rawkode are you sure ?

According to https://www.githubstatus.com/ GitHub Pages is back online

**Comment by nicolas-geniteau** [comment]
@lelithium Thanks for your help with pre-packaged charts.

@rawkode I just looked how `chart-releaser` works. It tries to download last version of index.yaml but if it can't, it assumes it is a new repository:

https://github.com/helm/chart-releaser/blob/master/pkg/releaser/releaser.go#L111

So during the last two releases github pages was down so it overrided index.yaml.

I think the easier should be to revert last two commits on `gh-pages` branch and re-run this two workflows from github actions (I am not if it is possible, I never used github actions)

**Comment by rawkode** [comment]
Because we merged during the downtime. it seems that our repo got rather confused.

I've bumped all the versions and forced a rebuild

**Comment by rawkode** [comment]
Ah, @nicolas-geniteau already commented to this effect. Thanks!

If anyone notices any further issues, please let us know :+1:

**Comment by lelithium** [comment]
Thanks !
