### ISSUE TITLE
Active Owners

### ISSUE THREAD

**Issue by powersj** [influxdata/helm-charts#593]
Hi @rawkode, @gitirabassi, @Aisuko, @naseemkullah, @deepaksood619,

The five of you are listed as code owners throughout this repo. I was curious if any or all of you are still actively interested in owning the code or have moved on? I would like to get a sense of current support and ownership.

Thanks!

**Comment by gitirabassi** [comment]
I’ve personally moved on and i’d like to be removed as code owner and maintainerThank you for checkingOn 17 Aug 2023, at 19:46, Joshua Powers ***@***.***> wrote:﻿
Hi @rawkode, @gitirabassi, @Aisuko, @naseemkullah, @deepaksood619,
The five of you are listed as code owners throughout this repo. I was curious if any or all of you are still actively interested in owning the code or have moved on? I would like to get a sense of current support and ownership.
Thanks!

**Comment by naseemkullah** [comment]
hi @powersj  - I've moved on. thanks!

**Comment by deepaksood619** [comment]
Hi @powersj I've moved on. Thanks!

**Comment by Aisuko** [comment]
Hi guys, I have moved on. Thanks.  Here is the related issue https://github.com/influxdata/influxdb/issues/16508

**Comment by rawkode** [comment]
Moved on. Thanks.

**Comment by powersj** [comment]
Thank you all for your responses.
