### ISSUE TITLE
Monitor chronograf 

### ISSUE THREAD

**Issue by ajayanaj** [influxdata/helm-charts#60]
Hello,

Is there any way we can set up monitor chronograf pods in kubernetes?
I tried to setup servicemonitor/podmonitor but I noticed that chronograf doesn't have the /metrics endpoint.
Could you please help me to setup a monitor on chronograf service/pod?
Thanks in advance

**Comment by russorat** [comment]
@ajayanaj thanks! there isn't much monitoring available of chronograf, but there is a `/ping` endpoint that let's you know if chronograf is running or not.

**Comment by ajayanaj** [comment]
@russorat thanks for the update,
