### ISSUE TITLE
telegraf-ds: allow configuration of kubernetes port

### ISSUE THREAD

**Issue by mgcrea** [influxdata/helm-charts#68]
Currently hardcoded to [`10250`](https://github.com/influxdata/helm-charts/blob/master/charts/telegraf-ds/templates/configmap.yaml#L38), would be great to be able to use a custom value.

Thanks!

**Comment by russorat** [comment]
@mgcrea thanks for the issue. would you be interested in submitting a PR?

**Comment by rawkode** [comment]
@mgcrea I'm not aware of any cloud providers running the control plane on a non-standard port; if you are, I'd love to know more.

Is this for bare metal, perhaps?

I'd be happy to help you submit the PR, but if your short on time I'll also put it together myself with some more context.

Thanks

**Comment by mgcrea** [comment]
@rawkode sorry for the long delay! Indeed this setup is for bare metal cluster created using [kubeadm](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm/), in my case the kube-apiserver port is 6443.

**Comment by mgcrea** [comment]
Tried again today and it looks like it is properly pulling metrics from port 10250, so I guess I mis-understood which API was targeted, now encountering #186. Sorry for the noise, closing.
