### ISSUE TITLE
[influxdb] Should support secret and volume mounts.

### ISSUE THREAD

**Issue by claymcleod** [influxdata/helm-charts#89]
Hi all,

I have a selfsigned certificate generated by `cert-manager` that I would like to use to configure HTTPS for Influxdb (between the ingress and the service). Unfortunately, I can't seem to find any options that support this. If such an avenue exists, could someone please point me to it?

**Comment by rawkode** [comment]
@claymcleod Does #88 provide everything you need?

**Comment by claymcleod** [comment]
Was just looking at that PR actually. Yes, it appears to, albiet for the telegraf chart instead of the influxdb one.

**Comment by rawkode** [comment]
@claymcleod I'll replicate the options to influxdb :+1:

**Comment by claymcleod** [comment]
Okay, great. I was actually doing just that — should I stop that effort? I'll give your PR a review once finished.

**Comment by rawkode** [comment]
@claymcleod No, please continue if you've started. Tag me in the PR when you're ready :+1:
