### ISSUE TITLE
[influxdb] conditionally add user/auth to backup script

### ISSUE THREAD

**Issue by naseemkullah** [influxdata/helm-charts#95]
cc @monotek @rawkode 

if `setDefaultUser.enabled: true` for example

**Comment by russorat** [comment]
@naseemkullah thanks for the issue. Would you be comfortable opening a PR?

**Comment by naseemkullah** [comment]
Yes but I am actually not entirely sure if its applicable finally.

https://docs.influxdata.com/influxdb/v1.8/administration/backup_and_restore/#configuring-remote-connections shows no example of passing auth params to a backup command on a remote host. Could you or @rawkode please confirm?

**Comment by airmonitor** [comment]
Apparently in ver 1.8 creds are not required anymore.

**Comment by alespour** [comment]
Backup does not require authentication.
